### ISSUE TITLE
Technical Debt Tracking Issue

### ISSUE THREAD

**Issue by dylanirlbeck** [xaptum/go-enf#20]
The technical debt of the `go-enf` library will be tracked in this issue. Additional tasks should be added when needed.

#### Code cleanup
- [ ] Add testing boilerplate (lots of redundant code with setting up test cases)
- [ ] Generalize response struct (parametrize the type of the struct in the `data` property)

#### Testing
- [ ] Improve test coverage. (Current coverage at ~ 58%)
- [ ] Integration Tests(?)

#### Documentation
- [ ] Add documentation to this library at `docs.xaptum.com`
- [ ] Have comments on all exported methods/structs
